[
  {
    "year":1903,
    "first_place":"Maurice Garin",
    "first_id":1,
    "first_country":"France",
    "first_team":"(none)",
    "second_place":"Lucien Pothier",
    "second_id":1,
    "second_country":"France",
    "second_team":"(none)",
    "third_place":"Fernand Augereau",
    "third_id":1,
    "third_country":"France",
    "third_team":"(none)",
    "stages":6,
    "distance":2428,
    "average_speed":25.679
  },
  {
    "year":1904,
    "first_place":"Henri Cornet",
    "first_id":1,
    "first_country":"France",
    "first_team":"Geboren Jardy",
    "second_place":"Jean-Baptiste Dortignacq",
    "second_id":1,
    "second_country":"France",
    "second_team":"(none)",
    "third_place":"Alois Catteau",
    "third_id":1,
    "third_country":"France",
    "third_team":"(none)",
    "stages":6,
    "distance":2428,
    "average_speed":25.265
  },
  {
    "year":1905,
    "first_place":"Louis Trousselier",
    "first_id":1,
    "first_country":"France",
    "first_team":"(none)",
    "second_place":"Hyppolite Aucouturier",
    "second_id":1,
    "second_country":"France",
    "second_team":"(none)",
    "third_place":"Jean-Baptiste Dortignacq",
    "third_id":1,
    "third_country":"France",
    "third_team":"(none)",
    "stages":11,
    "distance":2994,
    "average_speed":27.107
  },
  {
    "year":1906,
    "first_place":"Rene Pottier",
    "first_id":1,
    "first_country":"France",
    "first_team":"(none)",
    "second_place":"Georges Passerieu",
    "second_id":1,
    "second_country":"France",
    "second_team":"(none)",
    "third_place":"Louis Trousselier",
    "third_id":1,
    "third_country":"France",
    "third_team":"(none)",
    "stages":13,
    "distance":4545,
    "average_speed":24.463
  },
  {
    "year":1907,
    "first_place":"Lucien Mazan dit Petit-Breton",
    "first_id":1,
    "first_country":"France",
    "first_team":"(none)",
    "second_place":"Gustave Garrigou",
    "second_id":1,
    "second_country":"France",
    "second_team":"(none)",
    "third_place":"Emile Georget",
    "third_id":1,
    "third_country":"France",
    "third_team":"(none)",
    "stages":14,
    "distance":4488,
    "average_speed":28.47
  },
  {
    "year":1908,
    "first_place":"Lucien Mazan dit Petit-Breton",
    "first_id":1,
    "first_country":"France",
    "first_team":"(none)",
    "second_place":"Francois Faber",
    "second_id":2,
    "second_country":"Luxembourg",
    "second_team":"(none)",
    "third_place":"Georges Passerieu",
    "third_id":1,
    "third_country":"France",
    "third_team":"(none)",
    "stages":14,
    "distance":4488,
    "average_speed":28.74
  },
  {
    "year":1909,
    "first_place":"Francois Faber",
    "first_id":2,
    "first_country":"Luxembourg",
    "first_team":"Alcyon",
    "second_place":"Gustave Garrigou",
    "second_id":1,
    "second_country":"France",
    "second_team":"Alcyon",
    "third_place":"Jean Alavoine",
    "third_id":1,
    "third_country":"France",
    "third_team":"Alcyon",
    "stages":14,
    "distance":4497,
    "average_speed":28.658
  },
  {
    "year":1910,
    "first_place":"Octave Lapize",
    "first_id":1,
    "first_country":"France",
    "first_team":"Alcyon",
    "second_place":"Francois Faber",
    "second_id":2,
    "second_country":"Luxembourg",
    "second_team":"Alcyon",
    "third_place":"Gustave Garrigou",
    "third_id":1,
    "third_country":"France",
    "third_team":"Alcyon",
    "stages":15,
    "distance":4734,
    "average_speed":29.099
  },
  {
    "year":1911,
    "first_place":"Gustave Garrigou",
    "first_id":1,
    "first_country":"France",
    "first_team":"Alcyon",
    "second_place":"Paul Duboc",
    "second_id":1,
    "second_country":"France",
    "second_team":"La Francaise",
    "third_place":"Emile Georget",
    "third_id":1,
    "third_country":"France",
    "third_team":"La Francaise",
    "stages":15,
    "distance":5343,
    "average_speed":27.322
  },
  {
    "year":1912,
    "first_place":"Odile Defraye",
    "first_id":3,
    "first_country":"Belgium",
    "first_team":"Alcyon",
    "second_place":"Eugene Christophe",
    "second_id":1,
    "second_country":"France",
    "second_team":"Armor",
    "third_place":"Gustave Garrigou",
    "third_id":1,
    "third_country":"France",
    "third_team":"Alcyon",
    "stages":15,
    "distance":5289,
    "average_speed":27.763
  },
  {
    "year":1913,
    "first_place":"Philippe Thys",
    "first_id":3,
    "first_country":"Belgium",
    "first_team":"Peugeot",
    "second_place":"Gustave Garrigou",
    "second_id":1,
    "second_country":"France",
    "second_team":"Peugeot",
    "third_place":"Marcel Guysse",
    "third_id":3,
    "third_country":"Belgium",
    "third_team":"Peugeot",
    "stages":15,
    "distance":5287,
    "average_speed":26.715
  },
  {
    "year":1914,
    "first_place":"Philippe Thys",
    "first_id":3,
    "first_country":"Belgium",
    "first_team":"Peugeot-Wolber",
    "second_place":"Henri Pelissier",
    "second_id":1,
    "second_country":"France",
    "second_team":"Peugeot-Wolber",
    "third_place":"Jean Alavoine",
    "third_id":1,
    "third_country":"France",
    "third_team":"Peugeot-Wolber",
    "stages":15,
    "distance":5380,
    "average_speed":26.835
  },
  {
    "year":1919,
    "first_place":"Firmin Lambot",
    "first_id":3,
    "first_country":"Belgium",
    "first_team":"(none)",
    "second_place":"Jean Alavoine",
    "second_id":1,
    "second_country":"France",
    "second_team":"(none)",
    "third_place":"Eugene Christophe",
    "third_id":1,
    "third_country":"France",
    "third_team":"(none)",
    "stages":15,
    "distance":5560,
    "average_speed":24.056
  },
  {
    "year":1920,
    "first_place":"Philippe Thys",
    "first_id":3,
    "first_country":"Belgium",
    "first_team":"(none)",
    "second_place":"Hector Heusghem",
    "second_id":3,
    "second_country":"Belgium",
    "second_team":"(none)",
    "third_place":"Firmin Lambot",
    "third_id":3,
    "third_country":"Belgium",
    "third_team":"(none)",
    "stages":15,
    "distance":5503,
    "average_speed":24.072
  },
  {
    "year":1921,
    "first_place":"Leon Scieur",
    "first_id":3,
    "first_country":"Belgium",
    "first_team":"(none)",
    "second_place":"Hector Heusghem",
    "second_id":3,
    "second_country":"Belgium",
    "second_team":"(none)",
    "third_place":"Honore Barthelemy",
    "third_id":1,
    "third_country":"France",
    "third_team":"(none)",
    "stages":15,
    "distance":5485,
    "average_speed":24.724
  },
  {
    "year":1922,
    "first_place":"Firmin Lambot",
    "first_id":3,
    "first_country":"Belgium",
    "first_team":"(none)",
    "second_place":"Jean Alavoine",
    "second_id":1,
    "second_country":"France",
    "second_team":"(none)",
    "third_place":"Felix Sellier",
    "third_id":3,
    "third_country":"Belgium",
    "third_team":"(none)",
    "stages":15,
    "distance":5375,
    "average_speed":24.196
  },
  {
    "year":1923,
    "first_place":"Henri Pelissier",
    "first_id":1,
    "first_country":"France",
    "first_team":"(none)",
    "second_place":"Ottavio Bottecchia",
    "second_id":4,
    "second_country":"Italy",
    "second_team":"(none)",
    "third_place":"Romain Bellenger",
    "third_id":1,
    "third_country":"France",
    "third_team":"(none)",
    "stages":15,
    "distance":5386,
    "average_speed":24.233
  },
  {
    "year":1924,
    "first_place":"Ottavio Bottecchia",
    "first_id":4,
    "first_country":"Italy",
    "first_team":"Premiere Classe",
    "second_place":"Nicolas Frantz",
    "second_id":1,
    "second_country":"France",
    "second_team":"Premier Classe",
    "third_place":"Lucien Buysse",
    "third_id":3,
    "third_country":"Belgium",
    "third_team":"Premiere Classe",
    "stages":15,
    "distance":5425,
    "average_speed":24.25
  },
  {
    "year":1925,
    "first_place":"Ottavio Bottecchia",
    "first_id":4,
    "first_country":"Italy",
    "first_team":"Automoto-Hutchinson",
    "second_place":"Lucien Buysse",
    "second_id":3,
    "second_country":"Belgium",
    "second_team":"Automoto-Hutchinson",
    "third_place":"Bartolomeo Aimo",
    "third_id":4,
    "third_country":"Italy",
    "third_team":"Alcyon-Dunlop",
    "stages":18,
    "distance":5440,
    "average_speed":24.82
  },
  {
    "year":1926,
    "first_place":"Lucien Buysse",
    "first_id":3,
    "first_country":"Belgium",
    "first_team":"Automoto-Hutchinson",
    "second_place":"Nicolas Frantz",
    "second_id":1,
    "second_country":"France",
    "second_team":"Alcyon-Dunlop",
    "third_place":"Bartolomeo Aimo",
    "third_id":4,
    "third_country":"Italy",
    "third_team":"Alcyon-Dunlop",
    "stages":17,
    "distance":5745,
    "average_speed":24.273
  },
  {
    "year":1927,
    "first_place":"Nicolas Frantz",
    "first_id":1,
    "first_country":"France",
    "first_team":"Alcyon-Dunlop",
    "second_place":"Maurice De Waele",
    "second_id":3,
    "second_country":"Belgium",
    "second_team":"Labor-Dunlop",
    "third_place":"Julien Vervaecke",
    "third_id":3,
    "third_country":"Belgium",
    "third_team":"Alcyon-Dunlop",
    "stages":24,
    "distance":5340,
    "average_speed":27.224
  },
  {
    "year":1928,
    "first_place":"Andre Leducq",
    "first_id":1,
    "first_country":"France",
    "first_team":"Alcyon-Dunlop",
    "second_place":"Maurice De Waele",
    "second_id":3,
    "second_country":"Belgium",
    "second_team":"Alcyon-Dunlop",
    "third_place":"Tim Mertens",
    "third_id":3,
    "third_country":"Belgium",
    "third_team":"Thomann-Dunlop",
    "stages":22,
    "distance":5476,
    "average_speed":28.4
  },
  {
    "year":1929,
    "first_place":"Maurice De Waele",
    "first_id":3,
    "first_country":"Belgium",
    "first_team":"AS",
    "second_place":"Giuseppe Pancera",
    "second_id":4,
    "second_country":"Italy",
    "second_team":"AS",
    "third_place":"Jef Demuysere",
    "third_id":3,
    "third_country":"Belgium",
    "third_team":"AS",
    "stages":22,
    "distance":5257,
    "average_speed":28.319
  },
  {
    "year":1930,
    "first_place":"Andre Leducq",
    "first_id":1,
    "first_country":"France",
    "first_team":"France",
    "second_place":"Learco Guerra",
    "second_id":4,
    "second_country":"Italy",
    "second_team":"Italy",
    "third_place":"Antonin Magne",
    "third_id":1,
    "third_country":"France",
    "third_team":"Italy",
    "stages":21,
    "distance":4822,
    "average_speed":28
  },
  {
    "year":1931,
    "first_place":"Antonin Magne",
    "first_id":1,
    "first_country":"France",
    "first_team":"France",
    "second_place":"Jef Demuysere",
    "second_id":3,
    "second_country":"Belgium",
    "second_team":"Belgium",
    "third_place":"Antonio Pesenti",
    "third_id":4,
    "third_country":"Italy",
    "third_team":"Italy",
    "stages":24,
    "distance":5091,
    "average_speed":28.735
  },
  {
    "year":1932,
    "first_place":"Andre Leducq",
    "first_id":1,
    "first_country":"France",
    "first_team":"France",
    "second_place":"Kurt Stoepel",
    "second_id":11,
    "second_country":"Germany",
    "second_team":"Allemagne-Autriche",
    "third_place":"Francesco Camusso",
    "third_id":4,
    "third_country":"Italy",
    "third_team":"Italy",
    "stages":21,
    "distance":4479,
    "average_speed":29.047
  },
  {
    "year":1933,
    "first_place":"Georges Speicher",
    "first_id":1,
    "first_country":"France",
    "first_team":"France",
    "second_place":"Learco Guerra",
    "second_id":4,
    "second_country":"Italy",
    "second_team":"Italy",
    "third_place":"Giuseppe Martano",
    "third_id":4,
    "third_country":"Italy",
    "third_team":"Touristes-Routiers",
    "stages":23,
    "distance":4395,
    "average_speed":29.818
  },
  {
    "year":1934,
    "first_place":"Antonin Magne",
    "first_id":1,
    "first_country":"France",
    "first_team":"France",
    "second_place":"Giuseppe Martano",
    "second_id":4,
    "second_country":"Italy",
    "second_team":"Italy",
    "third_place":"Roger Lapebie",
    "third_id":1,
    "third_country":"France",
    "third_team":"France",
    "stages":23,
    "distance":4470,
    "average_speed":30.36
  },
  {
    "year":1935,
    "first_place":"Roman Maes",
    "first_id":3,
    "first_country":"Belgium",
    "first_team":"Belgium",
    "second_place":"Ambrogio Morelli",
    "second_id":4,
    "second_country":"Italy",
    "second_team":"Italy",
    "third_place":"Felicien Vervaecke",
    "third_id":3,
    "third_country":"Belgium",
    "third_team":"Belgium",
    "stages":21,
    "distance":4338,
    "average_speed":30.65
  },
  {
    "year":1936,
    "first_place":"Sylvere Maes",
    "first_id":3,
    "first_country":"Belgium",
    "first_team":"Belgium",
    "second_place":"Antonin Magne",
    "second_id":1,
    "second_country":"France",
    "second_team":"France",
    "third_place":"Felicien Vervaecke",
    "third_id":3,
    "third_country":"Belgium",
    "third_team":"Belgium",
    "stages":21,
    "distance":4418,
    "average_speed":31.108
  },
  {
    "year":1937,
    "first_place":"Guy Lapebie",
    "first_id":1,
    "first_country":"France",
    "first_team":"France",
    "second_place":"Mario Vicini",
    "second_id":4,
    "second_country":"Italy",
    "second_team":"Touristes Routiers",
    "third_place":"Leo Amberg",
    "third_id":6,
    "third_country":"Switzerland",
    "third_team":"Switzerland",
    "stages":20,
    "distance":4415,
    "average_speed":31.768
  },
  {
    "year":1938,
    "first_place":"Gino Bartali",
    "first_id":4,
    "first_country":"Italy",
    "first_team":"Italy",
    "second_place":"Felicien Vervaecke",
    "second_id":3,
    "second_country":"Belgium",
    "second_team":"Belgium",
    "third_place":"Victor Cosson",
    "third_id":1,
    "third_country":"France",
    "third_team":"France",
    "stages":23,
    "distance":2687,
    "average_speed":31.565
  },
  {
    "year":1939,
    "first_place":"Sylvere Maes",
    "first_id":3,
    "first_country":"Belgium",
    "first_team":"Belgium",
    "second_place":"Rene Vietto",
    "second_id":1,
    "second_country":"France",
    "second_team":"Sud-Est",
    "third_place":"Lucien Vlaemynck",
    "third_id":3,
    "third_country":"Belgium",
    "third_team":"Belgium",
    "stages":18,
    "distance":4224,
    "average_speed":31.986
  },
  {
    "year":1947,
    "first_place":"Jean Robic",
    "first_id":1,
    "first_country":"France",
    "first_team":"Ouest",
    "second_place":"Edourad Fachleitner",
    "second_id":1,
    "second_country":"France",
    "second_team":"France",
    "third_place":"Pierre Brambilla",
    "third_id":1,
    "third_country":"France",
    "third_team":"Italy",
    "stages":21,
    "distance":4640,
    "average_speed":31.412
  },
  {
    "year":1948,
    "first_place":"Gino Bartali",
    "first_id":4,
    "first_country":"Italy",
    "first_team":"Italy",
    "second_place":"Brik Schotte",
    "second_id":3,
    "second_country":"Belgium",
    "second_team":"Belgium",
    "third_place":"Guy Lapebie",
    "third_id":1,
    "third_country":"France",
    "third_team":"Centre-Sud Ouest",
    "stages":21,
    "distance":4922,
    "average_speed":33.442
  },
  {
    "year":1949,
    "first_place":"Fausto Coppi",
    "first_id":4,
    "first_country":"Italy",
    "first_team":"Italy",
    "second_place":"Gino Bartali",
    "second_id":4,
    "second_country":"Italy",
    "second_team":"Italy",
    "third_place":"Jacques Marinelli",
    "third_id":1,
    "third_country":"France",
    "third_team":"Ile de France",
    "stages":21,
    "distance":4808,
    "average_speed":32.121
  },
  {
    "year":1950,
    "first_place":"Ferdi Kubler",
    "first_id":6,
    "first_country":"Switzerland",
    "first_team":"Switzerland",
    "second_place":"Stan Ockers",
    "second_id":3,
    "second_country":"Belgium",
    "second_team":"Belgium",
    "third_place":"Louison Bobet",
    "third_id":1,
    "third_country":"France",
    "third_team":"France",
    "stages":22,
    "distance":4773,
    "average_speed":32.778
  },
  {
    "year":1951,
    "first_place":"Hugo Koblet",
    "first_id":6,
    "first_country":"Switzerland",
    "first_team":"Switzerland",
    "second_place":"Raphael Geminiani",
    "second_id":1,
    "second_country":"France",
    "second_team":"France",
    "third_place":"Lucien Lazarides",
    "third_id":1,
    "third_country":"France",
    "third_team":"France",
    "stages":24,
    "distance":4690,
    "average_speed":32.949
  },
  {
    "year":1952,
    "first_place":"Fausto Coppi",
    "first_id":4,
    "first_country":"Italy",
    "first_team":"Italy",
    "second_place":"Stan Ockers",
    "second_id":3,
    "second_country":"Belgium",
    "second_team":"Belgium",
    "third_place":"Bernardo Ruiz",
    "third_id":7,
    "third_country":"Spain",
    "third_team":"Spain",
    "stages":23,
    "distance":4898,
    "average_speed":32.233
  },
  {
    "year":1953,
    "first_place":"Louison Bobet",
    "first_id":1,
    "first_country":"France",
    "first_team":"France",
    "second_place":"Jean Mallejac",
    "second_id":1,
    "second_country":"France",
    "second_team":"Ouest",
    "third_place":"Giancarlo Astrua",
    "third_id":4,
    "third_country":"Italy",
    "third_team":"Italy",
    "stages":22,
    "distance":4476,
    "average_speed":34.593
  },
  {
    "year":1954,
    "first_place":"Louison Bobet",
    "first_id":1,
    "first_country":"France",
    "first_team":"France",
    "second_place":"Ferdi Kubler",
    "second_id":6,
    "second_country":"Switzerland",
    "second_team":"Switzerland",
    "third_place":"Fritz Schaer",
    "third_id":6,
    "third_country":"Switzerland",
    "third_team":"Switzerland",
    "stages":23,
    "distance":4656,
    "average_speed":33.229
  },
  {
    "year":1955,
    "first_place":"Louison Bobet",
    "first_id":1,
    "first_country":"France",
    "first_team":"France",
    "second_place":"Jean Brankart",
    "second_id":3,
    "second_country":"Belgium",
    "second_team":"Belgium",
    "third_place":"Charly Gaul",
    "third_id":2,
    "third_country":"Luxembourg",
    "third_team":"Luxembourg Mixte",
    "stages":22,
    "distance":4495,
    "average_speed":33.446
  },
  {
    "year":1956,
    "first_place":"Roger Walkowiak",
    "first_id":1,
    "first_country":"France",
    "first_team":"Nord Est-Centre",
    "second_place":"Gilbert Bauvin",
    "second_id":1,
    "second_country":"France",
    "second_team":"France",
    "third_place":"Jean Adriaenssens",
    "third_id":3,
    "third_country":"Belgium",
    "third_team":"Belgium",
    "stages":22,
    "distance":4498,
    "average_speed":36.268
  },
  {
    "year":1957,
    "first_place":"Jacques Anquetil",
    "first_id":1,
    "first_country":"France",
    "first_team":"(no data)",
    "second_place":"Marcel Janssens",
    "second_id":3,
    "second_country":"Belgium",
    "second_team":"(no data)",
    "third_place":"Adolf Christian",
    "third_id":14,
    "third_country":"Austria",
    "third_team":"(no data)",
    "stages":22,
    "distance":4665,
    "average_speed":34.25
  },
  {
    "year":1958,
    "first_place":"Charly Gaul",
    "first_id":2,
    "first_country":"Luxembourg",
    "first_team":"Pays Bas-Luxembourg",
    "second_place":"Vito Favero",
    "second_id":4,
    "second_country":"Italy",
    "second_team":"Italy",
    "third_place":"Raphael Geminiani",
    "third_id":1,
    "third_country":"France",
    "third_team":"Centre-Midi",
    "stages":24,
    "distance":4319,
    "average_speed":36.919
  },
  {
    "year":1959,
    "first_place":"Federico Bahamontes",
    "first_id":7,
    "first_country":"Spain",
    "first_team":"Spain",
    "second_place":"Henri Anglade",
    "second_id":1,
    "second_country":"France",
    "second_team":"Centre-Midi",
    "third_place":"Jacques Anquetil Fr",
    "third_id":1,
    "third_country":"France",
    "third_team":"France",
    "stages":22,
    "distance":4391,
    "average_speed":35.474
  },
  {
    "year":1960,
    "first_place":"Gastone Nencini",
    "first_id":4,
    "first_country":"Italy",
    "first_team":"Italy",
    "second_place":"Graziano Battistini",
    "second_id":4,
    "second_country":"Italy",
    "second_team":"Italy",
    "third_place":"Jean Adriaenssens",
    "third_id":3,
    "third_country":"Belgium",
    "third_team":"Belgium",
    "stages":21,
    "distance":4173,
    "average_speed":37.21
  },
  {
    "year":1961,
    "first_place":"Jacques Anquetil",
    "first_id":1,
    "first_country":"France",
    "first_team":"France",
    "second_place":"Guido Carlesi",
    "second_id":4,
    "second_country":"Italy",
    "second_team":"Italy",
    "third_place":"Charly Gaul",
    "third_id":2,
    "third_country":"Luxembourg",
    "third_team":"Suisse-Luxembourg",
    "stages":21,
    "distance":4397,
    "average_speed":36.033
  },
  {
    "year":1962,
    "first_place":"Jacques Anquetil",
    "first_id":1,
    "first_country":"France",
    "first_team":"ACBB-Saint Raphael-Helyett-Hutchinson",
    "second_place":"Jo Planckaert",
    "second_id":3,
    "second_country":"Belgium",
    "second_team":"Faema-Flandria-Clement",
    "third_place":"Raymond Poulidor",
    "third_id":1,
    "third_country":"France",
    "third_team":"Mercier-BP-Hutchinson",
    "stages":22,
    "distance":4274,
    "average_speed":37.317
  },
  {
    "year":1963,
    "first_place":"Jacques Anquetil",
    "first_id":1,
    "first_country":"France",
    "first_team":"V.C. XII-Saint Raphael-Gitane-Dunlop",
    "second_place":"Federico Bahamontes",
    "second_id":7,
    "second_country":"Spain",
    "second_team":"Margnat-Paloma-Motul-Dunlop",
    "third_place":"Jose Perez-Frances",
    "third_id":7,
    "third_country":"Spain",
    "third_team":"Ferrys",
    "stages":21,
    "distance":4137,
    "average_speed":37.092
  },
  {
    "year":1964,
    "first_place":"Jacques Anquetil",
    "first_id":1,
    "first_country":"France",
    "first_team":"V.C. XII-Saint Raphael-Gitane-Campagnolo",
    "second_place":"Raymond Poulidor",
    "second_id":1,
    "second_country":"France",
    "second_team":"Mercier-BP-Hutchinson",
    "third_place":"Federico Bahamontes",
    "third_id":7,
    "third_country":"Spain",
    "third_team":"Margnat-Paloma-Dunlop",
    "stages":22,
    "distance":4504,
    "average_speed":35.419
  },
  {
    "year":1965,
    "first_place":"Felice Gimondi",
    "first_id":4,
    "first_country":"Italy",
    "first_team":"Salvarani",
    "second_place":"Raymond Poulidor",
    "second_id":1,
    "second_country":"France",
    "second_team":"Mercier-BP-Hutchinson",
    "third_place":"Gianni Motta",
    "third_id":4,
    "third_country":"Italy",
    "third_team":"Molteni-Ignis",
    "stages":22,
    "distance":4188,
    "average_speed":35.886
  },
  {
    "year":1966,
    "first_place":"Lucien Aimar",
    "first_id":1,
    "first_country":"France",
    "first_team":"(no data)",
    "second_place":"Jan Janssen",
    "second_id":8,
    "second_country":"Netherlands",
    "second_team":"(no data)",
    "third_place":"Raymond Poulidor",
    "third_id":0,
    "third_country":"France",
    "third_team":"(no data)",
    "stages":22,
    "distance":4322,
    "average_speed":36.76
  },
  {
    "year":1967,
    "first_place":"Raymond Pingeon",
    "first_id":1,
    "first_country":"France",
    "first_team":"France",
    "second_place":"Julio Jimenez",
    "second_id":7,
    "second_country":"Spain",
    "second_team":"Spain",
    "third_place":"Franco Balmamion",
    "third_id":4,
    "third_country":"Italy",
    "third_team":"Primavera",
    "stages":22,
    "distance":4758,
    "average_speed":34.756
  },
  {
    "year":1968,
    "first_place":"Jan Janssen",
    "first_id":8,
    "first_country":"Netherlands",
    "first_team":"Netherlands",
    "second_place":"Herman Vanspringel",
    "second_id":3,
    "second_country":"Belgium",
    "second_team":"Belgium A",
    "third_place":"Ferdinand Bracke",
    "third_id":3,
    "third_country":"Belgium",
    "third_team":"Belgium B",
    "stages":22,
    "distance":4492,
    "average_speed":33.556
  },
  {
    "year":1969,
    "first_place":"Eddy Merckx",
    "first_id":3,
    "first_country":"Belgium",
    "first_team":"Faema",
    "second_place":"Raymond Pingeon",
    "second_id":1,
    "second_country":"France",
    "second_team":"Peugeot-BP-Michelin",
    "third_place":"Ramond Poulidor",
    "third_id":1,
    "third_country":"France",
    "third_team":"Mercier-BP-Hutchinson",
    "stages":22,
    "distance":4117,
    "average_speed":35.409
  },
  {
    "year":1970,
    "first_place":"Eddy Merckx",
    "first_id":3,
    "first_country":"Belgium",
    "first_team":"Faema-Faemino",
    "second_place":"Joop Zoetemelk",
    "second_id":8,
    "second_country":"Netherlands",
    "second_team":"Flandria-De Clerck-Kruger",
    "third_place":"Gosta Pettersson",
    "third_id":15,
    "third_country":"Sweden",
    "third_team":"Ferretti",
    "stages":23,
    "distance":4254,
    "average_speed":35.589
  },
  {
    "year":1971,
    "first_place":"Eddy Merckx",
    "first_id":3,
    "first_country":"Belgium",
    "first_team":"Molteni",
    "second_place":"Joop Zoetemelk",
    "second_id":8,
    "second_country":"Netherlands",
    "second_team":"Mars-Flandria",
    "third_place":"Lucien Van Impe",
    "third_id":3,
    "third_country":"Belgium",
    "third_team":"Sonolor-Lejeune",
    "stages":20,
    "distance":3608,
    "average_speed":38.084
  },
  {
    "year":1972,
    "first_place":"Eddy Merckx",
    "first_id":3,
    "first_country":"Belgium",
    "first_team":"Molteni",
    "second_place":"Felice Gimondi",
    "second_id":4,
    "second_country":"Italy",
    "second_team":"Salvarani",
    "third_place":"Raymond Poulidor",
    "third_id":1,
    "third_country":"France",
    "third_team":"Gan-Mercier-Hutchinson",
    "stages":20,
    "distance":3846,
    "average_speed":35.514
  },
  {
    "year":1973,
    "first_place":"Luis Ocana",
    "first_id":7,
    "first_country":"Spain",
    "first_team":"BIC",
    "second_place":"Bernard Thevenet",
    "second_id":1,
    "second_country":"France",
    "second_team":"Peugeot-BP",
    "third_place":"Jose-Manuel Fuente",
    "third_id":7,
    "third_country":"Spain",
    "third_team":"KAS",
    "stages":20,
    "distance":4090,
    "average_speed":33.407
  },
  {
    "year":1974,
    "first_place":"Eddy Merckx",
    "first_id":3,
    "first_country":"Belgium",
    "first_team":"Molteni",
    "second_place":"Raymond Poulidor",
    "second_id":1,
    "second_country":"France",
    "second_team":"Gan-Mercier",
    "third_place":"Vicente Lopez-Carril",
    "third_id":7,
    "third_country":"Spain",
    "third_team":"KAS",
    "stages":22,
    "distance":4098,
    "average_speed":35.241
  },
  {
    "year":1975,
    "first_place":"Bernard Thevenet",
    "first_id":1,
    "first_country":"France",
    "first_team":"Peugeot-BP",
    "second_place":"Eddy Merckx",
    "second_id":3,
    "second_country":"Belgium",
    "second_team":"Molteni",
    "third_place":"Lucien Van Impe",
    "third_id":3,
    "third_country":"Belgium",
    "third_team":"Gitane",
    "stages":22,
    "distance":4000,
    "average_speed":34.906
  },
  {
    "year":1976,
    "first_place":"Lucien Van Impe",
    "first_id":3,
    "first_country":"Belgium",
    "first_team":"Gitane-Campagnolo",
    "second_place":"Joop Zoetemelk",
    "second_id":8,
    "second_country":"Netherlands",
    "second_team":"Gan-Mercier-Hutchinson",
    "third_place":"Raymond Poulidor",
    "third_id":1,
    "third_country":"France",
    "third_team":"Gan-Mercier-Hutchinson",
    "stages":22,
    "distance":4017,
    "average_speed":34.518
  },
  {
    "year":1977,
    "first_place":"Bernard Thevenet",
    "first_id":1,
    "first_country":"France",
    "first_team":"Peugeot-Esso-Michelin",
    "second_place":"Hennie Kuiper",
    "second_id":8,
    "second_country":"Netherlands",
    "second_team":"TI-Raleigh",
    "third_place":"Lucien Van Impe",
    "third_id":3,
    "third_country":"Belgium",
    "third_team":"Lejeune-BP",
    "stages":22,
    "distance":4096,
    "average_speed":35.419
  },
  {
    "year":1978,
    "first_place":"Bernard Hinault",
    "first_id":1,
    "first_country":"France",
    "first_team":"Renault-Gitane",
    "second_place":"Joop Zoetemelk",
    "second_id":8,
    "second_country":"Netherlands",
    "second_team":"Miko-Mercier",
    "third_place":"Joaquim Agostinho",
    "third_id":16,
    "third_country":"Portugal",
    "third_team":"Velda-Lano-Flandria",
    "stages":22,
    "distance":3908,
    "average_speed":36.084
  },
  {
    "year":1979,
    "first_place":"Bernard Hinault",
    "first_id":1,
    "first_country":"France",
    "first_team":"Renault-Gitane",
    "second_place":"Joop Zoetemelk",
    "second_id":8,
    "second_country":"Netherlands",
    "second_team":"Miko-Mercier",
    "third_place":"Joaquim Agostinho",
    "third_id":16,
    "third_country":"Portugal",
    "third_team":"Flandria-Ca Va Seul",
    "stages":24,
    "distance":3765,
    "average_speed":36.513
  },
  {
    "year":1980,
    "first_place":"Joop Zoetemelk",
    "first_id":8,
    "first_country":"Netherlands",
    "first_team":"TI-Raleigh-Creda",
    "second_place":"Hennie Kuiper",
    "second_id":8,
    "second_country":"Netherlands",
    "second_team":"Peugeot-Esso-Michelin",
    "third_place":"Raymond Martin",
    "third_id":1,
    "third_country":"France",
    "third_team":"Miko-Mercier-Vivagel",
    "stages":22,
    "distance":3842,
    "average_speed":35.144
  },
  {
    "year":1981,
    "first_place":"Bernard Hinault",
    "first_id":1,
    "first_country":"France",
    "first_team":"Renault-Gitane",
    "second_place":"Lucien Van Impe",
    "second_id":3,
    "second_country":"Belgium",
    "second_team":"Boston-Mavic",
    "third_place":"Robert Alban",
    "third_id":1,
    "third_country":"France",
    "third_team":"La Redoute-Motobecane",
    "stages":22,
    "distance":3753,
    "average_speed":38.96
  },
  {
    "year":1982,
    "first_place":"Bernard Hinault",
    "first_id":1,
    "first_country":"France",
    "first_team":"Renault-Gitane",
    "second_place":"Joop Zoetemelk",
    "second_id":3,
    "second_country":"Belgium",
    "second_team":"Coop-Mercier-Mavic",
    "third_place":"Johan Van Der Velde",
    "third_id":8,
    "third_country":"Netherlands",
    "third_team":"TI-Raleigh-Campagnolo",
    "stages":21,
    "distance":3507,
    "average_speed":38.059
  },
  {
    "year":1983,
    "first_place":"Laurent Fignon",
    "first_id":1,
    "first_country":"France",
    "first_team":"Renault-Elf-Gitane",
    "second_place":"Angel Arroyo",
    "second_id":7,
    "second_country":"Spain",
    "second_team":"Reynolds",
    "third_place":"Peter Winnen",
    "third_id":8,
    "third_country":"Netherlands",
    "third_team":"TI-Raleigh-Campagnolo",
    "stages":22,
    "distance":3809,
    "average_speed":36.23
  },
  {
    "year":1984,
    "first_place":"Laurent Fignon",
    "first_id":1,
    "first_country":"France",
    "first_team":"Renault-Elf",
    "second_place":"Bernard Hinault",
    "second_id":1,
    "second_country":"France",
    "second_team":"La Vie Claire-Terraillon",
    "third_place":"Greg Lemond",
    "third_id":10,
    "third_country":"USA",
    "third_team":"Renault-Elf",
    "stages":23,
    "distance":4021,
    "average_speed":35.882
  },
  {
    "year":1985,
    "first_place":"Bernard Hinault",
    "first_id":1,
    "first_country":"France",
    "first_team":"La Vie Claire-Wonder-Radar",
    "second_place":"Greg Lemond",
    "second_id":10,
    "second_country":"USA",
    "second_team":"La Vie Claire-Wonder-Radar",
    "third_place":"Stephen Roche",
    "third_id":4,
    "third_country":"Italy",
    "third_team":"La Redoute",
    "stages":22,
    "distance":4109,
    "average_speed":36.232
  },
  {
    "year":1986,
    "first_place":"Greg Lemond",
    "first_id":9,
    "first_country":"USA",
    "first_team":"La Vie Claire-Wonder-Radar",
    "second_place":"Bernard Hinault",
    "second_id":1,
    "second_country":"France",
    "second_team":"La Vie Claire-Wonder-Radar",
    "third_place":"Urs Zimmerman",
    "third_id":6,
    "third_country":"Switzerland",
    "third_team":"Carrera Jeans",
    "stages":23,
    "distance":4094,
    "average_speed":37.02
  },
  {
    "year":1987,
    "first_place":"Stephen Roche",
    "first_id":4,
    "first_country":"Italy",
    "first_team":"Carrera Jeans",
    "second_place":"Pedro Delgado",
    "second_id":7,
    "second_country":"Spain",
    "second_team":"PDM",
    "third_place":"Jean-Francois Bernard",
    "third_id":1,
    "third_country":"France",
    "third_team":"Toshiba-Look-La Vie Claire",
    "stages":25,
    "distance":4231,
    "average_speed":36.645
  },
  {
    "year":1988,
    "first_place":"Pedro Delgado",
    "first_id":7,
    "first_country":"Spain",
    "first_team":"Reynolds",
    "second_place":"Steven Rooks",
    "second_id":8,
    "second_country":"Netherlands",
    "second_team":"PDM",
    "third_place":"Fabio Parra",
    "third_id":17,
    "third_country":"Colombia",
    "third_team":"Kelme",
    "stages":22,
    "distance":3286,
    "average_speed":38.909
  },
  {
    "year":1989,
    "first_place":"Greg Lemond",
    "first_id":9,
    "first_country":"USA",
    "first_team":"ADR-Agrigel-Bottecchia",
    "second_place":"Laurent Fignon",
    "second_id":1,
    "second_country":"France",
    "second_team":"Super U",
    "third_place":"Pedro Delgado",
    "third_id":7,
    "third_country":"Spain",
    "third_team":"Reynolds-Banesto",
    "stages":21,
    "distance":3285,
    "average_speed":37.487
  },
  {
    "year":1990,
    "first_place":"Greg Lemond",
    "first_id":9,
    "first_country":"USA",
    "first_team":"Z-Peugeot",
    "second_place":"Claudio Chiappucci",
    "second_id":4,
    "second_country":"Italy",
    "second_team":"Carrera Jeans-Vagabond",
    "third_place":"Erik Breukink",
    "third_id":8,
    "third_country":"Netherlands",
    "third_team":"PDM",
    "stages":21,
    "distance":3504,
    "average_speed":38.621
  },
  {
    "year":1991,
    "first_place":"Miguel Indurain",
    "first_id":7,
    "first_country":"Spain",
    "first_team":"Banesto",
    "second_place":"Gianni Bugno",
    "second_id":1,
    "second_country":"France",
    "second_team":"Gatorade-Chateau d'Ax",
    "third_place":"Claudio Chiappucci",
    "third_id":4,
    "third_country":"Italy",
    "third_team":"Carrera Jeans",
    "stages":22,
    "distance":3914,
    "average_speed":38.747
  },
  {
    "year":1992,
    "first_place":"Miguel Indurain",
    "first_id":7,
    "first_country":"Spain",
    "first_team":"Banesto",
    "second_place":"Claudio Chiappucci",
    "second_id":4,
    "second_country":"Italy",
    "second_team":"Carrera Jeans-Tassoni",
    "third_place":"Gianni Bugno",
    "third_id":4,
    "third_country":"Italy",
    "third_team":"Gatorade-Chateau d'Eax",
    "stages":21,
    "distance":3983,
    "average_speed":39.504
  },
  {
    "year":1993,
    "first_place":"Miguel Indurain",
    "first_id":7,
    "first_country":"Spain",
    "first_team":"Banesto",
    "second_place":"Tony Rominger",
    "second_id":6,
    "second_country":"Switzerland",
    "second_team":"Clas-Cajastur",
    "third_place":"Zenon Jaskula",
    "third_id":18,
    "third_country":"Poland",
    "third_team":"GB-MG-Maglificio",
    "stages":20,
    "distance":3714,
    "average_speed":38.709
  },
  {
    "year":1994,
    "first_place":"Miguel Indurain",
    "first_id":7,
    "first_country":"Spain",
    "first_team":"Banesto",
    "second_place":"Piotr Ugrumov",
    "second_id":12,
    "second_country":"Latvia",
    "second_team":"Gewiss-Ballan",
    "third_place":"Marco Pantani",
    "third_id":4,
    "third_country":"Italy",
    "third_team":"Carrera Jeans-Tassoni",
    "stages":21,
    "distance":3978,
    "average_speed":38.383
  },
  {
    "year":1995,
    "first_place":"Miguel Indurain",
    "first_id":7,
    "first_country":"Spain",
    "first_team":"Banesto",
    "second_place":"Alex Zulle",
    "second_id":6,
    "second_country":"Switzerland",
    "second_team":"Once",
    "third_place":"Bjarne Riis",
    "third_id":10,
    "third_country":"Denmark",
    "third_team":"Gewiss-Ballan",
    "stages":20,
    "distance":3653,
    "average_speed":39.193
  },
  {
    "year":1996,
    "first_place":"Bjarne Riis",
    "first_id":10,
    "first_country":"Denmark",
    "first_team":"Team Deutsche Telekom",
    "second_place":"Jan Ullrich",
    "second_id":11,
    "second_country":"Germany",
    "second_team":"Team Deutche Telekom",
    "third_place":"Richard Virenque",
    "third_id":1,
    "third_country":"France",
    "third_team":"Festina",
    "stages":21,
    "distance":3907,
    "average_speed":39.227
  },
  {
    "year":1997,
    "first_place":"Jan Ullrich",
    "first_id":11,
    "first_country":"Germany",
    "first_team":"Team Deutsche Telekom",
    "second_place":"Richard Virenque",
    "second_id":1,
    "second_country":"France",
    "second_team":"Festina Watches",
    "third_place":"Marco Pantani",
    "third_id":4,
    "third_country":"Italy",
    "third_team":"Mercatone-Uno",
    "stages":21,
    "distance":3950,
    "average_speed":39.237
  },
  {
    "year":1998,
    "first_place":"Marco Pantani",
    "first_id":4,
    "first_country":"Italy",
    "first_team":"Mercatone Uno-Bianchi",
    "second_place":"Jan Ullrich",
    "second_id":11,
    "second_country":"Germany",
    "second_team":"Team Deutche Telekom",
    "third_place":"Bobby Julich",
    "third_id":9,
    "third_country":"USA",
    "third_team":"Cofidis-Le Credit Par Telephone",
    "stages":21,
    "distance":3850,
    "average_speed":39.983
  },
  {
    "year":1999,
    "first_place":"Lance Armstrong",
    "first_id":9,
    "first_country":"USA",
    "first_team":"US Postal Service",
    "second_place":"Alex Zulle",
    "second_id":6,
    "second_country":"Switzerland",
    "second_team":"Banesto",
    "third_place":"Fernando Escartin",
    "third_id":7,
    "third_country":"Spain",
    "third_team":"Kelme-Costa Blanca",
    "stages":20,
    "distance":3870,
    "average_speed":40.276
  },
  {
    "year":2000,
    "first_place":"Lance Armstrong",
    "first_id":9,
    "first_country":"USA",
    "first_team":"US Postal Service",
    "second_place":"Jan Ullrich",
    "second_id":11,
    "second_country":"Germany",
    "second_team":"Team Deutche Telekom",
    "third_place":"Joseba Beloki",
    "third_id":7,
    "third_country":"Spain",
    "third_team":"Festina Watches",
    "stages":21,
    "distance":3662.5,
    "average_speed":39.57
  },
  {
    "year":2001,
    "first_place":"Lance Armstrong",
    "first_id":9,
    "first_country":"USA",
    "first_team":"US Postal Service",
    "second_place":"Jan Ullrich",
    "second_id":11,
    "second_country":"Germany",
    "second_team":"Team Deutche Telekom",
    "third_place":"Joseba Beloki",
    "third_id":7,
    "third_country":"Spain",
    "third_team":"Kelme",
    "stages":20,
    "distance":0,
    "average_speed":0
  },
  {
    "year":2002,
    "first_place":"Lance Armstrong",
    "first_id":9,
    "first_country":"USA",
    "first_team":"US Postal Service",
    "second_place":"Joseba Beloki",
    "second_id":7,
    "second_country":"Spain",
    "second_team":"Once-Eroski",
    "third_place":"Raimondas Rumsas",
    "third_id":18,
    "third_country":"Lithuania",
    "third_team":"Lampre-Daikin",
    "stages":20,
    "distance":0,
    "average_speed":0
  },
  {
    "year":2003,
    "first_place":"Lance Armstrong",
    "first_id":9,
    "first_country":"USA",
    "first_team":"US Postal Service-Berry Floor",
    "second_place":"Jan Ullrich",
    "second_id":11,
    "second_country":"Germany",
    "second_team":"Team Bianchi",
    "third_place":"Alexandre Vinokourov",
    "third_id":19,
    "third_country":"Kazakhstan",
    "third_team":"Team Telekom",
    "stages":20,
    "distance":0,
    "average_speed":0
  },
  {
    "year":2004,
    "first_place":"Lance Armstrong",
    "first_id":9,
    "first_country":"USA",
    "first_team":"US Postal Service-Berry Floor",
    "second_place":"Andreas Kleden",
    "second_id":11,
    "second_country":"Germany",
    "second_team":"T-Mobile Team",
    "third_place":"Ivan Basso",
    "third_id":4,
    "third_country":"Italy",
    "third_team":"Team CSC",
    "stages":20,
    "distance":0,
    "average_speed":0
  },
  {
    "year":2005,
    "first_place":"Lance Armstrong",
    "first_id":9,
    "first_country":"USA",
    "first_team":"Discovery Channel Team",
    "second_place":"Ivan Basso",
    "second_id":4,
    "second_country":"Italy",
    "second_team":"Team CSC",
    "third_place":"Jan Ullrich",
    "third_id":11,
    "third_country":"Germany",
    "third_team":"T-Mobile Team",
    "stages":21,
    "distance":0,
    "average_speed":0
  },
  {
    "year":2006,
    "first_place":"Oscar Pereiro Sio",
    "first_id":7,
    "first_country":"Spain",
    "first_team":"Caisse d'Epargne-Illes Balears",
    "second_place":"Andreas Kleden",
    "second_id":11,
    "second_country":"Germany",
    "second_team":"T-Mobile Team",
    "third_place":"Carlos Sastre",
    "third_id":7,
    "third_country":"Spain",
    "third_team":"Team CSC",
    "stages":20,
    "distance":3657.1,
    "average_speed":0
  },
  {
    "year":2007,
    "first_place":"Alberto Contador",
    "first_id":7,
    "first_country":"Spain",
    "first_team":"Discovery Channel Team",
    "second_place":"Cadel Evans",
    "second_id":13,
    "second_country":"Australia",
    "second_team":"Predictor-Lotto",
    "third_place":"Levi Leipheimer",
    "third_id":9,
    "third_country":"USA",
    "third_team":"Discovery Channel Team",
    "stages":20,
    "distance":3569.9,
    "average_speed":0
  },
  {
    "year":2008,
    "first_place":"Carlos Sastre",
    "first_id":7,
    "first_country":"Spain",
    "first_team":"Team CSC Saxo Bank",
    "second_place":"Cadel Evans",
    "second_id":13,
    "second_country":"Australia",
    "second_team":"Silence-Lotto",
    "third_place":"Bernhard Kohl",
    "third_id":14,
    "third_country":"Austria",
    "third_team":"Gerolsteiner",
    "stages":21,
    "distance":3559.5,
    "average_speed":0
  },
  {
    "year":2009,
    "first_place":"Alberto Contador",
    "first_id":7,
    "first_country":"Spain",
    "first_team":"Astana",
    "second_place":"Andy Schleck",
    "second_id":8,
    "second_country":"Netherlands",
    "second_team":"Team Saxo Bank",
    "third_place":"Lance Armstrong",
    "third_id":9,
    "third_country":"USA",
    "third_team":"Astana",
    "stages":21,
    "distance":3459.5,
    "average_speed":0
  },
  {
    "year":2010,
    "first_place":"Alberto Contador",
    "first_id":7,
    "first_country":"Spain",
    "first_team":"Astana",
    "second_place":"Andy Schleck",
    "second_id":8,
    "second_country":"Netherlands",
    "second_team":"Team Saxo Bank",
    "third_place":"Denis Menchov",
    "third_id":20,
    "third_country":"Russia",
    "third_team":"Rabobank",
    "stages":20,
    "distance":3641.4,
    "average_speed":0
  }
]
